"""0001 initial design.

Revision ID: 0001
Revises: 0000
Create Date: 2020-08-16 02:39:13.031887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0001"
down_revision = "0000"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("updated_on", sa.DateTime(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("color", sa.String(length=7), nullable=False),
        sa.PrimaryKeyConstraint(
            "id", name="project_id_primary_key_constraint"
        ),
        sa.UniqueConstraint("slug", name="project_slug_unique_constraint"),
    )
    op.create_table(
        "tag",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("updated_on", sa.DateTime(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("color", sa.String(length=7), nullable=False),
        sa.PrimaryKeyConstraint("id", name="tag_id_primary_key_constraint"),
        sa.UniqueConstraint("slug", name="tag_slug_unique_constraint"),
    )
    op.create_table(
        "task",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("updated_on", sa.DateTime(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("color", sa.String(length=7), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("default", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
            ondelete="CASCADE",
            name="task_project_fk_constraint",
        ),
        sa.PrimaryKeyConstraint("id", name="task_id_primary_key_constraint"),
        sa.UniqueConstraint(
            "project_id",
            "slug",
            name="task_project_id_task_slug_unique_constraint",
        ),
    )
    op.create_table(
        "entry",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("updated_on", sa.DateTime(), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("description", sa.String(length=2047), nullable=False),
        sa.Column("notes", sa.String(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.Column("duration", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
            ondelete="CASCADE",
            name="entry_project_fk_constraint",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["task.id"],
            ondelete="CASCADE",
            name="entry_task_fk_constraint",
        ),
        sa.PrimaryKeyConstraint("id", name="entry_id_primary_key_constraint"),
    )
    op.create_table(
        "entry_tag",
        sa.Column("entry_id", sa.String(length=36), nullable=False),
        sa.Column("tag_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["entry_id"],
            ["entry.id"],
            ondelete="CASCADE",
            name="entry_tag_entry_fk_constraint",
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tag.id"],
            ondelete="CASCADE",
            name="entry_tag_tag_fk_constraint",
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("entry_tag")
    op.drop_table("entry")
    op.drop_table("task")
    op.drop_table("tag")
    op.drop_table("project")
    # ### end Alembic commands ###
